/*
 * Copyright Charles Gray.
 * All rights Reserved.
 */
package v.File;

import c.CallmaidUtils;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import m.Common;
import m.db.ResultSetTableModel;
import v.Log.Logfile;
import c.UIMainC;


/**
 *
 * @author chas
 */
public class ExportCallsign extends javax.swing.JFrame {
private final Logfile logger;
private final UIMainC mainC;



    /**
     * Creates new form ExportCallsign
     */
public ExportCallsign() 
  {
  this.logger = Common.logger;
  initComponents();
  this.setVisible(true);
  this.populateStatesComboBox();
  this.populateCountriesComboBox();
  this.updateStatus();
  this.mainC = new UIMainC(logger);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDateFirstEntry = new javax.swing.JLabel();
        jTextFieldDateFirstEntry = new javax.swing.JTextField();
        jLabelDateLastEntry = new javax.swing.JLabel();
        jTextFieldDateLastEntry = new javax.swing.JTextField();
        jLabelCallsign = new javax.swing.JLabel();
        jTextFieldCallsign = new javax.swing.JTextField();
        jLabelMaidenhead = new javax.swing.JLabel();
        jTextFieldMaidenhead = new javax.swing.JTextField();
        jLabelState = new javax.swing.JLabel();
        jComboBoxState = new javax.swing.JComboBox<>();
        jLabelCountry = new javax.swing.JLabel();
        jComboBoxCountry = new javax.swing.JComboBox<>();
        jLabelCQZone = new javax.swing.JLabel();
        jTextFieldCQZone = new javax.swing.JTextField();
        jLabelITUZone = new javax.swing.JLabel();
        jTextFieldITUZone = new javax.swing.JTextField();
        jLabelModDate = new javax.swing.JLabel();
        jComboBoxModDate = new javax.swing.JComboBox<>();
        jFormattedTextFieldModDate = new javax.swing.JFormattedTextField();
        jCheckBoxWorked = new javax.swing.JCheckBox();
        jButtonConfigureTextOutput = new javax.swing.JButton();
        jLabelTotalCallmaidRecords = new javax.swing.JLabel();
        jTextFieldTotalCallmaidRecords = new javax.swing.JTextField();
        jButtonExportSelectedtoCSV = new javax.swing.JButton();
        jButtonExportAlltoCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export Callsign Table");

        jLabelDateFirstEntry.setText("Date First Entry");

        jTextFieldDateFirstEntry.setText("jTextField1");
        jTextFieldDateFirstEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateFirstEntryActionPerformed(evt);
            }
        });

        jLabelDateLastEntry.setText("Date Last Entry");

        jTextFieldDateLastEntry.setText("jTextField1");

        jLabelCallsign.setText("Callsign");

        jLabelMaidenhead.setText("Maidenhead");

        jTextFieldMaidenhead.setToolTipText("Maidenhead prefix");

        jLabelState.setText("State");

        jComboBoxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        jLabelCountry.setText("Country");

        jComboBoxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        jComboBoxCountry.setMinimumSize(new java.awt.Dimension(580, 20));
        jComboBoxCountry.setPreferredSize(new java.awt.Dimension(680, 20));

        jLabelCQZone.setText("CQ Zone");

        jLabelITUZone.setText("ITU Zone");

        jLabelModDate.setText("Mod. Date");

        jComboBoxModDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<=", ">=" }));
        jComboBoxModDate.setSelectedItem(">=");

        jFormattedTextFieldModDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldModDate.setToolTipText("MM/DD/YY");

        jCheckBoxWorked.setText("Worked");

        jButtonConfigureTextOutput.setText("Configure Text Output");
        jButtonConfigureTextOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigureTextOutputActionPerformed(evt);
            }
        });

        jLabelTotalCallmaidRecords.setText("Total callsign records");

        jTextFieldTotalCallmaidRecords.setText("0");

        jButtonExportSelectedtoCSV.setText("Export Selected to CSV");
        jButtonExportSelectedtoCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportSelectedtoCSVActionPerformed(evt);
            }
        });

        jButtonExportAlltoCSV.setText("Export All to CSV");
        jButtonExportAlltoCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportAlltoCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelCQZone, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCQZone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelITUZone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldITUZone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabelModDate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxModDate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldModDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCheckBoxWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTotalCallmaidRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldTotalCallmaidRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelMaidenhead, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldMaidenhead, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelDateFirstEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldDateFirstEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDateLastEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelState, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldDateLastEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConfigureTextOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButtonExportSelectedtoCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonExportAlltoCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateFirstEntry)
                    .addComponent(jTextFieldDateFirstEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateLastEntry)
                    .addComponent(jTextFieldDateLastEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCallsign)
                    .addComponent(jTextFieldCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaidenhead)
                    .addComponent(jTextFieldMaidenhead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelState)
                    .addComponent(jComboBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCQZone)
                    .addComponent(jTextFieldCQZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelITUZone)
                    .addComponent(jTextFieldITUZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModDate)
                    .addComponent(jComboBoxModDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldModDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxWorked))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfigureTextOutput)
                    .addComponent(jButtonExportSelectedtoCSV)
                    .addComponent(jButtonExportAlltoCSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalCallmaidRecords)
                    .addComponent(jTextFieldTotalCallmaidRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateFirstEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateFirstEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateFirstEntryActionPerformed

    private void jButtonConfigureTextOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigureTextOutputActionPerformed
       new ConfigureTextOutput();
    }//GEN-LAST:event_jButtonConfigureTextOutputActionPerformed

    private void jButtonExportSelectedtoCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportSelectedtoCSVActionPerformed
     CallmaidUtils cmu = new CallmaidUtils(logger,Common.prodb,Common.debugFlag);
     String SQLClause = mainC.buildSQLClauseCallmaid(
             this.jTextFieldCallsign.getText(), this.jTextFieldMaidenhead.getText(),
             this.jTextFieldCQZone.getText(), this.jTextFieldITUZone.getText(),
             this.jFormattedTextFieldModDate.getText(), this.jComboBoxCountry.getSelectedIndex(),
             this.jComboBoxState.getSelectedIndex(), this.jComboBoxModDate.getSelectedIndex(),
             this.jCheckBoxWorked.isSelected());  
     if(SQLClause.equals(""))return;
     //cmu.displayCallmaid(SQLClause);    
     logger.e("Hey, add some code here");
    }//GEN-LAST:event_jButtonExportSelectedtoCSVActionPerformed

    private void jButtonExportAlltoCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportAlltoCSVActionPerformed
        Common.prodb.exportTableToCSV("CALLMAID", "CALLSIGNS");
    }//GEN-LAST:event_jButtonExportAlltoCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportCallsign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportCallsign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportCallsign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportCallsign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportCallsign().setVisible(true);
            }
        });
    }

/*    
private boolean populateStates()
  {
  // Populate combobox of state names
  this.jComboBoxState.removeAllItems();
  this.jComboBoxState.addItem("None");
  ResultSetTableModel rstm = Common.prodb.queryGeneric("select * from STATES order by name");
  if(rstm==null){logger.e("Failed query of STATES.  Aborting."); System.exit(0);}
  ArrayList<String> alstatenames =Common.prodb.columnToArrayList(rstm,2);
  alstatenames.forEach((n) -> this.jComboBoxState.addItem((String)n));  
  this.alstateabbr = Common.prodb.columnToArrayList(rstm,1); // ArrayList<String>
  //System.out.println("flagme. state name[0]=" + alstatenames.get(0) + ", combobox[0]=" + jComboBoxState.getItemAt(0) + ", abbr=" + alstateabbr.get(0));
  return true;    
  }// end method populateStates
*/
private boolean populateCountriesComboBox()
  {
  // Populate combobox of country names
  this.jComboBoxCountry.removeAllItems();
  this.jComboBoxCountry.addItem("None");
  Common.prodb.alcountrynames.forEach((n) -> this.jComboBoxCountry.addItem((String)n));     
  //System.out.println("flagme. country name[0]=" + alcountrynames.get(0) + ", combobox[0]=" + jComboBoxCountry.getItemAt(0) + ", abbr=" + alcountryabbr.get(0));
  return true;
  }// end method populateCountries

private boolean populateStatesComboBox()
  {
  // Populate combobox of state names
  this.jComboBoxState.removeAllItems();
  this.jComboBoxState.addItem("None");
  Common.prodb.alstatenames.forEach((n) -> this.jComboBoxState.addItem((String)n));     
  return true;
  }// end method populateStateComboBox

    
    
private void updateStatus()
  {
  DecimalFormat df = new DecimalFormat("###,###,###");
  this.jTextFieldTotalCallmaidRecords.setText(df.format(Common.prodb.totalRecordsInTable("CALLMAID")));
  String strDate=Common.prodb.allTxtDateAsString("first");
  if(strDate==null) JOptionPane.showMessageDialog(null, "The CALLMAID database table is empty.  This is normal for first program startup.","Alert",JOptionPane.ERROR_MESSAGE);
  if(strDate==null)strDate="None";
  this.jTextFieldDateFirstEntry.setText(strDate);
  strDate=Common.prodb.allTxtDateAsString("last");
  if(strDate==null)strDate="None";
  this.jTextFieldDateLastEntry.setText(strDate);
  }     
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfigureTextOutput;
    private javax.swing.JButton jButtonExportAlltoCSV;
    private javax.swing.JButton jButtonExportSelectedtoCSV;
    private javax.swing.JCheckBox jCheckBoxWorked;
    public javax.swing.JComboBox<String> jComboBoxCountry;
    private javax.swing.JComboBox<String> jComboBoxModDate;
    public javax.swing.JComboBox<String> jComboBoxState;
    private javax.swing.JFormattedTextField jFormattedTextFieldModDate;
    private javax.swing.JLabel jLabelCQZone;
    private javax.swing.JLabel jLabelCallsign;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDateFirstEntry;
    private javax.swing.JLabel jLabelDateLastEntry;
    private javax.swing.JLabel jLabelITUZone;
    private javax.swing.JLabel jLabelMaidenhead;
    private javax.swing.JLabel jLabelModDate;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JLabel jLabelTotalCallmaidRecords;
    private javax.swing.JTextField jTextFieldCQZone;
    private javax.swing.JTextField jTextFieldCallsign;
    private javax.swing.JTextField jTextFieldDateFirstEntry;
    private javax.swing.JTextField jTextFieldDateLastEntry;
    private javax.swing.JTextField jTextFieldITUZone;
    private javax.swing.JTextField jTextFieldMaidenhead;
    private javax.swing.JTextField jTextFieldTotalCallmaidRecords;
    // End of variables declaration//GEN-END:variables
} // end class ExportCallsign
