/*
 * Copyright Charles Gray.
 * All rights Reserved.
 * flagme Add code to require user to populate critical parameters such as database
 */
package v;

import javax.swing.JOptionPane;
import m.Common;
import v.File.PropertiesUtils;

/**
 *
 * @author chas
 */
public class SetProperties extends javax.swing.JFrame {
private final PropertiesUtils puObj;
public boolean retval;


    /**
     * Creates new form SetProperties
     */
public SetProperties() 
  {
  initComponents();
  this.setVisible(true);
  this.puObj = new PropertiesUtils("properties.txt");
  if(puObj.getValidStatus()==false)
    {    
    JOptionPane.showMessageDialog(null, "Properties file=" + Common.logfileName + " not found.\n"
        + "Set Properties will create a new properties.txt properties file.", 
      "Fatal ERROR", JOptionPane.ERROR_MESSAGE);
    return;
  }
  this.jTextFieldLogfile.setText(Common.logfileName);
  this.jTextFieldYourCallsign.setText(Common.callsign);
  if(Common.debugFlag)this.jCheckBoxDebugFlag.setSelected(true);
  this.jTextFieldwsjtxfile.setText(Common.wsjtxFile);
  //System.out.println("DBType=" + Common.DBType);
  this.jComboBoxDatabaseType.setSelectedItem(Common.DBType);
  this.jTextFieldDatabaseServer.setText(Common.DBServer);
  this.jTextFieldDatabaseName.setText(Common.DBName);
  this.jTextFieldDatabaseUsername.setText(Common.DBUsername);
  this.jTextFieldDatabasePassword.setText(Common.DBPassword);
  this.jTextFieldHomeMaidenhead.setText(Common.homeQTH);
  this.jTextFieldEntityFile.setText(Common.entityFile);
  this.jTextFieldzipcodefile.setText(Common.zipcodeFile);
  this.jTextFieldAutodelete.setText(String.valueOf(Common.autodelete));
  this.jTextFieldQueryRowLimit.setText(String.valueOf(Common.queryRowLimit));
  this.jTextFieldUDPPort.setText(String.valueOf(Common.UDPPort));
  this.jTextFieldIPAddress.setText(Common.localIPAddress);
  if(Common.qthrealtime)this.jCheckBoxqthrealtime.setSelected(true);
  if(Common.adminFlag)this.jCheckBoxadminFlag.setSelected(true);
  this.jComboBoxLookAndFeel.setSelectedItem(Common.lookAndFeel);
  } // end constructor





private void submit()
{
String tStr;
puObj.setParameterS("logfile",this.jTextFieldLogfile.getText());
if(this.jCheckBoxDebugFlag.isSelected()){puObj.setParameterS("debugFlag","true");Common.debugFlag=true;}
else {puObj.setParameterS("debugFlag","false"); Common.debugFlag=false;}
puObj.setParameterS("wsjtxFile",this.jTextFieldwsjtxfile.getText());
Common.wsjtxFile=this.jTextFieldwsjtxfile.getText();
puObj.setParameterS("DBType", (String)this.jComboBoxDatabaseType.getSelectedItem());
puObj.setParameterS("DBServer", this.jTextFieldDatabaseServer.getText());
puObj.setParameterS("DBName", this.jTextFieldDatabaseName.getText());
puObj.setParameterS("DBUsername",this.jTextFieldDatabaseUsername.getText());
tStr=this.jTextFieldDatabasePassword.getText();
if(tStr != null && !tStr.equals("")) puObj.setParameterS("DBPassword", this.jTextFieldDatabasePassword.getText());
puObj.setParameterS("homeQTH", this.jTextFieldHomeMaidenhead.getText());
Common.homeQTH=this.jTextFieldHomeMaidenhead.getText();
puObj.setParameterS("callsign", this.jTextFieldYourCallsign.getText());
Common.callsign=this.jTextFieldYourCallsign.getText();
puObj.setParameterS("entityFile", this.jTextFieldEntityFile.getText());
puObj.setParameterS("zipcodeFile", this.jTextFieldzipcodefile.getText());
puObj.setParameterS("autodelete", this.jTextFieldAutodelete.getText());
if(Integer.parseInt(this.jTextFieldQueryRowLimit.getText()) < 2000)
  {
   JOptionPane.showMessageDialog(null, "Minimum value for query row limit is 2000.","Input Erro",JOptionPane.ERROR_MESSAGE);
  this.jTextFieldQueryRowLimit.setText("2000");
  }
puObj.setParameterS("queryRowLimit", this.jTextFieldQueryRowLimit.getText());
puObj.setParameterS("UDPPort", this.jTextFieldUDPPort.getText());
puObj.setParameterS("localIPAddress", this.jTextFieldIPAddress.getText());
if(this.jCheckBoxqthrealtime.isSelected()){puObj.setParameterS("qthrealtime","true");Common.qthrealtime=true;}
else {puObj.setParameterS("qthrealtime","false"); Common.qthrealtime=false;}
if(this.jCheckBoxadminFlag.isSelected()){puObj.setParameterS("adminFlag","true");Common.adminFlag=true;}
else {puObj.setParameterS("adminFlag","false"); Common.adminFlag=false;}
puObj.setParameterS("lookAndFeel", (String)this.jComboBoxLookAndFeel.getSelectedItem());
//System.out.println(puObj.loadParameterS("callsign"));
puObj.save();
} // end submit()


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelYourCallsign = new javax.swing.JLabel();
        jTextFieldYourCallsign = new javax.swing.JTextField();
        jLabelLogfile = new javax.swing.JLabel();
        jTextFieldLogfile = new javax.swing.JTextField();
        jCheckBoxDebugFlag = new javax.swing.JCheckBox();
        jLabelwsjtxfile = new javax.swing.JLabel();
        jTextFieldwsjtxfile = new javax.swing.JTextField();
        jComboBoxDatabaseType = new javax.swing.JComboBox<>();
        jLabelDatabaseType = new javax.swing.JLabel();
        jLabelDatabaseServer = new javax.swing.JLabel();
        jTextFieldDatabaseServer = new javax.swing.JTextField();
        jLabelDatabaseName = new javax.swing.JLabel();
        jTextFieldDatabaseName = new javax.swing.JTextField();
        jLabelDatabasePassword = new javax.swing.JLabel();
        jTextFieldDatabasePassword = new javax.swing.JTextField();
        jLabelHomeMaidenhead = new javax.swing.JLabel();
        jTextFieldHomeMaidenhead = new javax.swing.JTextField();
        jLabelEntityFile = new javax.swing.JLabel();
        jTextFieldEntityFile = new javax.swing.JTextField();
        jLabelzipcodefile = new javax.swing.JLabel();
        jTextFieldzipcodefile = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jLabelDebugflag = new javax.swing.JLabel();
        jLabelAdminOption = new javax.swing.JLabel();
        jLabelDatabaseUsername = new javax.swing.JLabel();
        jTextFieldDatabaseUsername = new javax.swing.JTextField();
        jLabelAutodelete = new javax.swing.JLabel();
        jTextFieldAutodelete = new javax.swing.JTextField();
        jLabelQueryRowLimit = new javax.swing.JLabel();
        jTextFieldQueryRowLimit = new javax.swing.JTextField();
        jLabelNetworkOptions = new javax.swing.JLabel();
        jLabelUDPPort = new javax.swing.JLabel();
        jTextFieldUDPPort = new javax.swing.JTextField();
        jLabelIPAddress = new javax.swing.JLabel();
        jTextFieldIPAddress = new javax.swing.JTextField();
        jCheckBoxqthrealtime = new javax.swing.JCheckBox();
        jCheckBoxadminFlag = new javax.swing.JCheckBox();
        jLabelLookAndFeel = new javax.swing.JLabel();
        jComboBoxLookAndFeel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Properties");
        setAlwaysOnTop(true);

        jLabelYourCallsign.setText("Your Callsign");

        jLabelLogfile.setText("Logfile");

        jCheckBoxDebugFlag.setText("Debug Flag");

        jLabelwsjtxfile.setText("Wsjtx File");

        jComboBoxDatabaseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MariaDB", "Derby_res" }));

        jLabelDatabaseType.setText("Database Type");

        jLabelDatabaseServer.setText("Database Server");

        jLabelDatabaseName.setText("Database Name");

        jLabelDatabasePassword.setText("Database Password");

        jLabelHomeMaidenhead.setText("Home Maidenhead");

        jLabelEntityFile.setText("Entity File");

        jTextFieldEntityFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEntityFileActionPerformed(evt);
            }
        });

        jLabelzipcodefile.setText("Zip code file");

        jButtonSave.setText("Submit");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelDebugflag.setText("Enhanced Log");

        jLabelAdminOption.setText("Administrator Options");

        jLabelDatabaseUsername.setText("Database Username");

        jLabelAutodelete.setText("Autodelete in days");

        jTextFieldAutodelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAutodeleteActionPerformed(evt);
            }
        });

        jLabelQueryRowLimit.setText("Query Row Limit");

        jTextFieldQueryRowLimit.setToolTipText("Maximum rows returned by any query.  Minimum 2000");
        jTextFieldQueryRowLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQueryRowLimitActionPerformed(evt);
            }
        });

        jLabelNetworkOptions.setText("Network Options");

        jLabelUDPPort.setText("UDP Port");

        jLabelIPAddress.setText("Local IP Address");

        jTextFieldIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPAddressActionPerformed(evt);
            }
        });

        jCheckBoxqthrealtime.setText("HamQTH real time");

        jCheckBoxadminFlag.setText("adminFlag");
        jCheckBoxadminFlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxadminFlagActionPerformed(evt);
            }
        });

        jLabelLookAndFeel.setText("Look and Feel");

        jComboBoxLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metal", "System", "Motif", "GTK", "Windows" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabelEntityFile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEntityFile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAutodelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAutodelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelDatabaseUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDatabaseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDatabaseServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelwsjtxfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLogfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelYourCallsign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDatabaseType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDebugflag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldYourCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldLogfile)
                                    .addComponent(jCheckBoxDebugFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldwsjtxfile)
                                    .addComponent(jComboBoxDatabaseType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDatabaseServer)
                                    .addComponent(jTextFieldDatabaseName)
                                    .addComponent(jTextFieldDatabaseUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelHomeMaidenhead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDatabasePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAdminOption)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldDatabasePassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldHomeMaidenhead, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelQueryRowLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldQueryRowLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelzipcodefile, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldzipcodefile))
                                    .addComponent(jLabelNetworkOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelUDPPort, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldUDPPort, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxqthrealtime)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxadminFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYourCallsign)
                    .addComponent(jTextFieldYourCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogfile)
                    .addComponent(jTextFieldLogfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxDebugFlag)
                    .addComponent(jLabelDebugflag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldwsjtxfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelwsjtxfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDatabaseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatabaseType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatabaseServer)
                    .addComponent(jTextFieldDatabaseServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatabaseName)
                    .addComponent(jTextFieldDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatabaseUsername)
                    .addComponent(jTextFieldDatabaseUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatabasePassword)
                    .addComponent(jTextFieldDatabasePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomeMaidenhead)
                    .addComponent(jTextFieldHomeMaidenhead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQueryRowLimit)
                    .addComponent(jTextFieldQueryRowLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelNetworkOptions)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUDPPort)
                    .addComponent(jTextFieldUDPPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIPAddress)
                    .addComponent(jTextFieldIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxqthrealtime)
                    .addComponent(jCheckBoxadminFlag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLookAndFeel)
                    .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelAdminOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEntityFile)
                    .addComponent(jTextFieldEntityFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelzipcodefile)
                    .addComponent(jTextFieldzipcodefile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutodelete)
                    .addComponent(jTextFieldAutodelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
      this.submit();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldQueryRowLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQueryRowLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQueryRowLimitActionPerformed

    private void jTextFieldAutodeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAutodeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAutodeleteActionPerformed

    private void jTextFieldEntityFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEntityFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEntityFileActionPerformed

    private void jTextFieldIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPAddressActionPerformed

    private void jCheckBoxadminFlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxadminFlagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxadminFlagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxDebugFlag;
    private javax.swing.JCheckBox jCheckBoxadminFlag;
    private javax.swing.JCheckBox jCheckBoxqthrealtime;
    private javax.swing.JComboBox<String> jComboBoxDatabaseType;
    private javax.swing.JComboBox<String> jComboBoxLookAndFeel;
    private javax.swing.JLabel jLabelAdminOption;
    private javax.swing.JLabel jLabelAutodelete;
    private javax.swing.JLabel jLabelDatabaseName;
    private javax.swing.JLabel jLabelDatabasePassword;
    private javax.swing.JLabel jLabelDatabaseServer;
    private javax.swing.JLabel jLabelDatabaseType;
    private javax.swing.JLabel jLabelDatabaseUsername;
    private javax.swing.JLabel jLabelDebugflag;
    private javax.swing.JLabel jLabelEntityFile;
    private javax.swing.JLabel jLabelHomeMaidenhead;
    private javax.swing.JLabel jLabelIPAddress;
    private javax.swing.JLabel jLabelLogfile;
    private javax.swing.JLabel jLabelLookAndFeel;
    private javax.swing.JLabel jLabelNetworkOptions;
    private javax.swing.JLabel jLabelQueryRowLimit;
    private javax.swing.JLabel jLabelUDPPort;
    private javax.swing.JLabel jLabelYourCallsign;
    private javax.swing.JLabel jLabelwsjtxfile;
    private javax.swing.JLabel jLabelzipcodefile;
    private javax.swing.JTextField jTextFieldAutodelete;
    private javax.swing.JTextField jTextFieldDatabaseName;
    private javax.swing.JTextField jTextFieldDatabasePassword;
    private javax.swing.JTextField jTextFieldDatabaseServer;
    private javax.swing.JTextField jTextFieldDatabaseUsername;
    private javax.swing.JTextField jTextFieldEntityFile;
    private javax.swing.JTextField jTextFieldHomeMaidenhead;
    private javax.swing.JTextField jTextFieldIPAddress;
    private javax.swing.JTextField jTextFieldLogfile;
    private javax.swing.JTextField jTextFieldQueryRowLimit;
    private javax.swing.JTextField jTextFieldUDPPort;
    private javax.swing.JTextField jTextFieldYourCallsign;
    private javax.swing.JTextField jTextFieldwsjtxfile;
    private javax.swing.JTextField jTextFieldzipcodefile;
    // End of variables declaration//GEN-END:variables
}
