/*
 * Copyright Charles Gray.
 * All rights Reserved.
 */
package v;
import UDP.UDPThreadManager;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumn;
import javax.swing.table.TableCellRenderer;
import v.ShowMessage;
import v.Log.Logfile;


/**
 *
 * @author chas
 */
public class WSJTXStatus extends javax.swing.JFrame {
public final UDPThreadManager udptm;
//private final Color lightred = new Color(50,0,0);  
String CQRespCallsign;
private final boolean debugFlag;
private final Logfile logger;

    /**
     * Creates new form WSJTXStatus
     */
public WSJTXStatus(UDPThreadManager sw, Logfile logger, boolean debugFlag) 
  {
  this.logger = logger;
  this.debugFlag = debugFlag;;
  this.udptm = sw;
  this.setTitle(this.udptm.title);
  this.setLocation(500, 200);
  if(SwingUtilities.isEventDispatchThread()) logger.println("WSJTXStatus is on the EventDispatchThread");
  else logger.println("WSJTXStatus is NOT on the EventDispatchThread");
  this.addWindowListener(new WindowAdapter()
    {
    public void windowClosing(WindowEvent e) 
      {
      //System.out.println("window close event");
      logger.tprintln("WSJTXStatus is closing and calling UDPThreadManager.terminate()");
      udptm.terminate();
      //System.out.println("post terminate");
      }
    });
  initComponents();
  this.setVisible(true);
  if(!debugFlag)
    {
    jTableEligibleQSOs.getColumnModel().getColumn(7).setMinWidth(0);
    jTableEligibleQSOs.getColumnModel().getColumn(7).setMaxWidth(0);
    jTableEligibleQSOs.getColumnModel().getColumn(8).setMinWidth(0);
    jTableEligibleQSOs.getColumnModel().getColumn(8).setMaxWidth(0);
    jTableEligibleQSOs.getColumnModel().getColumn(9).setMinWidth(0);
    jTableEligibleQSOs.getColumnModel().getColumn(9).setMaxWidth(0);
    }
  //jTableEligibleQSOs.setValueAt("KM4SDB", 0, 0);
  //jTableEligibleQSOs.setValueAt("EL91ij", 0, 1);
  //jTableEligibleQSOs.setValueAt(-12, 0, 2);

  
  //jTableEligibleQSOs.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
//  Class tcrclss = jTableEligibleQSOs.getColumnClass(0);
 // TableCellRenderer tcr = jTableEligibleQSOs.getDefaultRenderer(tcrclss);
 //javax.swing.table.DefaultTableCellRenderer tcrxx; 
  //tcr = jTableEligibleQSOs.getCellRenderer(0,0);
 
dfr dfrObj = new dfr();   // This is where the magic happens
jTableEligibleQSOs.setDefaultRenderer(Object.class, dfrObj);
jTableEligibleQSOs.setDefaultRenderer(Integer.class, dfrObj);
jTableEligibleQSOs.setDefaultRenderer(Boolean.class, dfrObj);
//System.out.println("RowSelectionAllowed=" + this.jTableEligibleQSOs.getRowSelectionAllowed());
  this.jTableEligibleQSOs.setRowSelectionAllowed(true);
 // System.out.println("RowSelectionAllowed=" + this.jTableEligibleQSOs.getRowSelectionAllowed());
  //jTableEligibleQSOs.clearSelection();
  //if(jTableEligibleQSOs.getRowCount() > 1) this.jTableEligibleQSOs.setRowSelectionInterval(2,2);
  this.jTableEligibleQSOs.setAutoResizeMode(jTableEligibleQSOs.AUTO_RESIZE_ALL_COLUMNS); // flagme
  } // end constructor



public class dfr extends DefaultTableCellRenderer
  
  //jTableEligibleQSOs.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
   {
   public dfr(){};
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
      {
        if(column==8) // color column
          {
          int rowcolor = (Integer)table.getValueAt(row, column);
          }
        //System.out.println("getTableCellRendererCompontent value=" + value);
        final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        c.setBackground(Color.white);
        if(isSelected)
          {
          //logger.println("Setting row " + row + " to red.");
          c.setBackground(Color.red);
          udptm.transmitCQResponse(row);
          jTableEligibleQSOs.clearSelection();
          }
        //else c.setBackground(row % 2 == 0 ? Color.RED : Color.WHITE);
        
        return c;
      }
};  // end class dfr

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessReceived = new javax.swing.JLabel();
        jLabelIncoming = new javax.swing.JLabel();
        jTextFieldMessReceived = new javax.swing.JTextField();
        jLabelOutgoing = new javax.swing.JLabel();
        jLabelMessProcessed = new javax.swing.JLabel();
        jTextFieldMessProcessed = new javax.swing.JTextField();
        jLabelBufferSize = new javax.swing.JLabel();
        jTextFieldQueueSize = new javax.swing.JTextField();
        jLabelLastHeartbeat = new javax.swing.JLabel();
        jTextFieldHeartbeat = new javax.swing.JTextField();
        jLabelNewCallsigns = new javax.swing.JLabel();
        jTextFieldNewCallsignRecords = new javax.swing.JTextField();
        jLabelOnlineQueries = new javax.swing.JLabel();
        jTextFieldOnlineQueries = new javax.swing.JTextField();
        jLabelHamOnlineResponses = new javax.swing.JLabel();
        jTextFieldOnlineResponses = new javax.swing.JTextField();
        jLabelUpdatedCallsignRecords = new javax.swing.JLabel();
        jTextFieldUpdatedCallsignRecs = new javax.swing.JTextField();
        jButtonClearWindows = new javax.swing.JButton();
        jButtonCloseWSJTX = new javax.swing.JButton();
        jPanelEligibleQSOs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEligibleQSOs = new javax.swing.JTable()
        {
            /*
            public int selectedRow;
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column)
            {
                Color lightred = new Color(255,200,200);
                Component c = super.prepareRenderer(renderer, row, column);
                System.out.println("prepareRenderer");
                if (!isRowSelected(row)) c.setBackground(Color.white);
                else c.setBackground(lightred);
                return c;
            }
            */
        }
        ;
        jLabelCQList = new javax.swing.JLabel();
        jCheckBoxNotWorked = new javax.swing.JCheckBox();
        jLabelRSSIgt = new javax.swing.JLabel();
        jTextFieldRSSIgt = new javax.swing.JTextField();
        jCheckBoxIncResp = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldContest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelMessReceived.setText("Messages Received");

        jLabelIncoming.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelIncoming.setText("Incoming");

        jTextFieldMessReceived.setText("0");

        jLabelOutgoing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOutgoing.setText("Outgoing");

        jLabelMessProcessed.setText("Messages Processed");

        jTextFieldMessProcessed.setText("0");

        jLabelBufferSize.setText("Queue Size");

        jLabelLastHeartbeat.setText("Last Heartbeat");

        jLabelNewCallsigns.setText("New Callsign Records");

        jLabelOnlineQueries.setText("Online Queries");

        jLabelHamOnlineResponses.setText("Online Responses");

        jLabelUpdatedCallsignRecords.setText("Updated Callsign Recs");

        jButtonClearWindows.setText("Clear WSJT-X Band Activity");
        jButtonClearWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearWindowsActionPerformed(evt);
            }
        });

        jButtonCloseWSJTX.setText("Close WSJT-X");
        jButtonCloseWSJTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseWSJTXActionPerformed(evt);
            }
        });

        jTableEligibleQSOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Callsign", "Maidenhead", "RSS", "Contest", "Worked", "Watch", "TimeElapsed", "TimeStart", "Color", "MessageRec"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEligibleQSOs);

        jLabelCQList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCQList.setText("Calls eligible for QSO");

        jCheckBoxNotWorked.setText("Not Worked");

        jLabelRSSIgt.setText("RSSI >");

        jCheckBoxIncResp.setText("Inc. Resp.");

        jLabel1.setText("Contest");

        javax.swing.GroupLayout jPanelEligibleQSOsLayout = new javax.swing.GroupLayout(jPanelEligibleQSOs);
        jPanelEligibleQSOs.setLayout(jPanelEligibleQSOsLayout);
        jPanelEligibleQSOsLayout.setHorizontalGroup(
            jPanelEligibleQSOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelEligibleQSOsLayout.createSequentialGroup()
                .addComponent(jCheckBoxNotWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRSSIgt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRSSIgt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxIncResp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContest, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEligibleQSOsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCQList, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanelEligibleQSOsLayout.setVerticalGroup(
            jPanelEligibleQSOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEligibleQSOsLayout.createSequentialGroup()
                .addComponent(jLabelCQList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEligibleQSOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNotWorked)
                    .addComponent(jLabelRSSIgt)
                    .addComponent(jTextFieldRSSIgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxIncResp)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldContest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMessReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldOnlineQueries)
                                    .addComponent(jTextFieldNewCallsignRecords)
                                    .addComponent(jTextFieldMessReceived, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                            .addComponent(jButtonClearWindows))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelUpdatedCallsignRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jLabelHamOnlineResponses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldUpdatedCallsignRecs, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(jTextFieldOnlineResponses)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMessProcessed, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMessProcessed, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCloseWSJTX, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelOnlineQueries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNewCallsigns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelEligibleQSOs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBufferSize, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelIncoming, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126)
                                        .addComponent(jLabelOutgoing, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldQueueSize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabelLastHeartbeat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHeartbeat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBufferSize)
                    .addComponent(jTextFieldQueueSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastHeartbeat)
                    .addComponent(jTextFieldHeartbeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIncoming)
                            .addComponent(jLabelOutgoing))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMessProcessed)
                            .addComponent(jTextFieldMessProcessed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMessReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMessReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewCallsigns)
                    .addComponent(jTextFieldNewCallsignRecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpdatedCallsignRecords)
                    .addComponent(jTextFieldUpdatedCallsignRecs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelOnlineQueries)
                        .addComponent(jTextFieldOnlineQueries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHamOnlineResponses)
                        .addComponent(jTextFieldOnlineResponses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEligibleQSOs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearWindows)
                    .addComponent(jButtonCloseWSJTX))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearWindowsActionPerformed
       if(!this.udptm.serverWorker.udpwsjtx.messageType3Transmit())
           logger.e("Failed to transmit WSJTX clear window message.");
    }//GEN-LAST:event_jButtonClearWindowsActionPerformed

    private void jButtonCloseWSJTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseWSJTXActionPerformed
        if(!this.udptm.serverWorker.udpwsjtx.messageType6Transmit())
        logger.e("Failed to transmit WSJTX close message.");
    }//GEN-LAST:event_jButtonCloseWSJTXActionPerformed

public boolean removeRow(int rowNum)
  {
  try{((DefaultTableModel)jTableEligibleQSOs.getModel()).removeRow(rowNum);}
  catch(ArrayIndexOutOfBoundsException aioob)
    {
    logger.ee("In deleteCQsResponded().removeRow() ArrayIndexOutOfBounds.",aioob); 
    return false;
    }
  return true;
  }
      
public boolean insertRow(Object[] rowData)
  {
  ((DefaultTableModel)jTableEligibleQSOs.getModel()).insertRow(0, rowData);      
  return true;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearWindows;
    private javax.swing.JButton jButtonCloseWSJTX;
    public javax.swing.JCheckBox jCheckBoxIncResp;
    public javax.swing.JCheckBox jCheckBoxNotWorked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBufferSize;
    private javax.swing.JLabel jLabelCQList;
    private javax.swing.JLabel jLabelHamOnlineResponses;
    private javax.swing.JLabel jLabelIncoming;
    private javax.swing.JLabel jLabelLastHeartbeat;
    private javax.swing.JLabel jLabelMessProcessed;
    private javax.swing.JLabel jLabelMessReceived;
    private javax.swing.JLabel jLabelNewCallsigns;
    private javax.swing.JLabel jLabelOnlineQueries;
    private javax.swing.JLabel jLabelOutgoing;
    private javax.swing.JLabel jLabelRSSIgt;
    private javax.swing.JLabel jLabelUpdatedCallsignRecords;
    private javax.swing.JPanel jPanelEligibleQSOs;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableEligibleQSOs;
    public javax.swing.JTextField jTextFieldContest;
    public javax.swing.JTextField jTextFieldHeartbeat;
    public javax.swing.JTextField jTextFieldMessProcessed;
    public javax.swing.JTextField jTextFieldMessReceived;
    public javax.swing.JTextField jTextFieldNewCallsignRecords;
    public javax.swing.JTextField jTextFieldOnlineQueries;
    public javax.swing.JTextField jTextFieldOnlineResponses;
    public javax.swing.JTextField jTextFieldQueueSize;
    public javax.swing.JTextField jTextFieldRSSIgt;
    public javax.swing.JTextField jTextFieldUpdatedCallsignRecs;
    // End of variables declaration//GEN-END:variables
}
